name: Feature Request
description: Suggest an idea for UPatch

body:
  - type: markdown
    attributes:
      value: |
        Please write in English. Keep requests within the scope of the UPatch manager. Kernel core features belong upstream.
  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      options:
        - label: I have searched the existing issues
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
