name: Feature Request
description: Suggest an idea for UPatch. English ONLY.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## **STOP AND READ**
        - This repository is **ENGLISH ONLY**. Requests in other languages will be closed.
        - Ensure you have read `CONTRIBUTING.md`.
        - Keep requests within the scope of the UPatch manager. Kernel core features belong upstream.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: "I have searched the existing issues."
          required: true
        - label: "My title is in English."
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
